### ISSUE TITLE
`.chain` ends up with an unindexed collector

### ISSUE THREAD

**Issue by mathstuf** [nikomatsakis/rayon#175]
The rayon-using code [here](https://gitlab.kitware.com/utils/rust-git-hooks/blob/bf4d8edd769cf491bf92df07ee0004d0931ab9e8/src/run.rs#L77) is causing this error after merging of #166:

```
panicked at 'internal error: entered unreachable code: CollectConsumer must be indexed!', /home/boeckb/.cargo/git/checkouts/rayon-2af7db7e4550ecfd/e2d8593dd0d870d54b1c7cd92342560f830f035d/src/par_iter/collect/consumer.rs:94
```

**Comment by cuviper** [comment]
Thanks, I'll try to look at this tonight.  Though if you or someone else wants to investigate sooner, please go ahead!

**Comment by cuviper** [comment]
At a quick glance though, our test `check_chain` still works if converted to a simple `collect` that will go through that faux-unindexed path, so it's not so easy to just blame `chain`.

**Comment by mathstuf** [comment]
Feel free to fix the summary to be more accurate; I'm not that familiar with the internals here.

**Comment by cuviper** [comment]
As soon as I know what's going on, I will. :)

**Comment by cuviper** [comment]
Oh.  `ChainIter::drive_unindexed` *directly* calls `split_off`, which is the thing asserting here.  AFAICS it's the only adapter that behaves anything like this, so it really is just a `chain` problem.  It was masked from my quick glance earlier because all of those in `check_chain` are behind a `zip` and `enumerate` which will take care of indexed driving earlier.
