### ISSUE TITLE
Implementing a parallel iterator should require `unsafe`.

### ISSUE THREAD

**Issue by bluss** [nikomatsakis/rayon#178]
I notice that the source code says that the implementation of ExactParallelIterator::len is safety-critical.

It is possible to implement parallel iterators without saying `unsafe` at any point, so this seems counter to the usual rules of safety in Rust, at some point must the implementor explicitly write under the contract of it all by saying `unsafe`.

That's a very loose understanding of it, isn't it, but I think that matches conventions.

**Comment by cuviper** [comment]
Ah, [we had this discussion on gitter](https://gitter.im/rayon-rs/Lobby?at=582ccc3788fa21d53c2f74e3) a few weeks ago, and determined that comment is out of date.  It used to be safety-critical because `collect_into` trusted it, but nowadays collection is more paranoid.  I think we can just remove that safety note.

**Comment by bluss** [comment]
Thanks. This was addressed in 870bf5b13132fad690bb30c21762c9949e09cbf7
