### ISSUE TITLE
`Producer::split_at` inconsistency

### ISSUE THREAD

**Issue by bluss** [nikomatsakis/rayon#215]
`Producer::split_at(index: usize)` says for a sequence of length `N`, index must be less than `N`.

```rust
    /// Split into two producers; one produces items `0..index`, the
    /// other `index..N`. Index must be less than `N`.
    fn split_at(self, index: usize) -> (Self, Self);
```

The ChainProducer impl does not follow this rule.

The reason I ask is that:

- It would be expected that `index <= N`, which is usual for splitting vectors.
- However `index < N` is very useful, since the split between the last element and the end is only easy to implement for sequences where the "pointer to one past the end" is allowed.
  - This is not the case for a reversed view of a vector (“stride -1”); we are not allowed to have a slice that points to the element before the start of the vector's memory, even if it has length 0.
  - (ndarray already implements splitting using the `index <= N` rule in some cases, but it has extra complexity to do so, and I ran into this when trying to implement `split_at` for more iterators that have exactly the negative stride case to care for).

I suppose the simple fix is to update docs to align with the implementation's perception of the `Producer` trait's interface.

**Comment by bluss** [comment]
ChainProducer relies on a lot of noop splitting. That's fine for slices, but maybe it should do something else there anyway, something involving an enum of `Both(A, B), One(A), Two(B)`.

**Comment by cuviper** [comment]
> It would be expected that index <= N, which is usual for splitting vectors.

Yes, this is my expectation, especially since it's also legal at the other boundary, `split_at(0)`.
(although the docs here don't actually specify behavior at 0)

> However index < N is very useful, since the split between the last element and the end is only easy to implement for sequences where the "pointer to one past the end" is allowed.

I don't really understand why this is a problem for a reversed view.  It seems to me that this should map naturally, such that `split_at(index)` becomes a reversed `N-index`, and at the edges `split_at(0)` maps to `N`, `split_at(N)` maps to `0`.

If you're treating these as stride pointers, there has to be some way to include the 0th index regardless of where we're splitting, like referring to some `i..0`.  I think I'd treat a reversed range as left-exclusive, `(a,b]` for `a >= b`, so your "pointer to one past the end" is the left value in this case.

> ChainProducer relies on a lot of noop splitting. That's fine for slices, but maybe it should do something else there anyway, something involving an enum of Both(A, B), One(A), Two(B).

I did go down this road when implementing `chain`, but it felt like the code was much uglier IIRC.  Maybe I made it harder than it needed to be. :)  If you want to experiment along these lines, feel free!

**Comment by bluss** [comment]
I'm sorry, that's confusion on my part. It's just striding in general. With stride = 2 there is no guaranteed one past the end pointer in the original direction either.

**Comment by cuviper** [comment]
So what's the actual problem with stride=2?  Is it because you do `N*2` internally, which may overflow?

**Comment by bluss** [comment]
First, I think the natural course of action is to fix the documentation, unless there is a clear opening for changing the protocol to really be `index < N`.

This is meant to illustrate why `[T]`’s approach to .split_at() does not translate to strided views:

```rust
// p is logically <0, 2>, a strided view of `v`
// The representation is { ptr: *const T, len: usize, stride: isize }
let v = [0, 1, 2];
let p = v.as_ptr();
let len = 2;
let stride = 2;

// the strided view has element pointers `p.offset(stride * i)`:
[p.offset(stride * 0), p.offset(stride * 1)]

// split at 1 -- ok
// let (p1, p2) = p.split_at(1);
let p1 = p;
let p1_len = 1;
let p1_stride = stride;
let p2 = p.offset(1 * stride);
let p2_len = len - 1;
let p2_stride = stride;

// split at 2 
// let (p1, p2) = p.split_at(2);
let p1 = p;
let p1_len = 2;
let p1_stride = stride;
let p2 = p.offset(2 * stride); // ERROR This pointer two past the end of `v`
let p2_len = len - 2;
let p2_stride = stride;
```
