### ISSUE TITLE
Consider using the `std::iter::Sum`/`Product` traits

### ISSUE THREAD

**Issue by cuviper** [nikomatsakis/rayon#252]
Instead of the current `SumOp`/`ProductOp`, we could use the same traits as `Iterator`, potentially enabling use with more than just the primitive types.

```rust
// Iterator:
fn sum<S>(self) -> S
    where S: Sum<Self::Item>

// ParallelIterator now:
fn sum(self) -> Self::Item
    where SumOp: ReduceOp<Self::Item>

// perhaps use Sum for folding, Add for reducing
fn sum(self) -> Self::Item
    where Self::Item: Sum + Add<Output=Self::Item>

// or even this, allowing sums by reference
// (but this is sometimes bad for type inference)
fn sum<S>(self) -> S
    where S: Sum<Self::Item> + Add<Output=S>
```

**Comment by cuviper** [comment]
This would be a breaking change, so we should decide before 1.0.

**Comment by nikomatsakis** [comment]
Hmm, I have to think about this. I designed the current trait setup pretty specifically with an eye for eventually optimizing them with SIMD and so forth using specialization -- and because we want to assume that the addition operation is associative, which the stdlib traits probably don't require. (It also happens to map pretty nicely to what I've seen in other projects (i.e., Cilk), I think, though I'd have to dig up a citation). *But* I agree it'd be nice to not have it.

**Comment by cuviper** [comment]
I figured it was just because `Sum` and `Product` were stabilized relatively recently, only in 1.12.  And hey! That's our current baseline! :)

Couldn't they still be specialized behind the scenes?  And the associativity can be a matter of documentation, just as we do for `reduce`.  In fact, `sum` and `product` already mention the associative requirements too.

**Comment by nikomatsakis** [comment]
@cuviper 

> I figured it was just because Sum and Product were stabilized relatively recently, only in 1.12.

Well, that might also be true -- I just know that those other concerns (associativity, etc) were on my mind, to be honest I don't remember the state of libstd at the time =)
