### ISSUE TITLE
Error with 0.7.0: no method named `zip` found for type rayon::collections::hash_map::IntoIter

### ISSUE THREAD

**Issue by robinst** [nikomatsakis/rayon#302]
I had the following code that worked with 0.6.0 (adapted from [this comment](https://github.com/nikomatsakis/rayon/issues/55#issuecomment-202402159)):

```rust
let files: HashMap<String, String> = ...;
let senders: Vec<_> = files.iter().map(|_| sender.clone()).collect();
files.into_par_iter()
    .zip(senders)
    .for_each(|((path, content), sender)| {
        // do the work
    });
```

With Rayon 0.7.0, it no longer compiles:

```
error: no method named `zip` found for type `rayon::collections::hash_map::IntoIter<std::string::String, std::string::String>` in the current scope
   --> src/bin/extract.rs:146:10
    |
146 |         .zip(senders)
    |          ^^^
    = note: the method `zip` exists but the following trait bounds were not satisfied: `rayon::collections::hash_map::IntoIter<std::string::String, std::string::String> : std::iter::Iterator`
```

Was that an intentional change in the API? I'm just wondering if this changed by mistake or if it was never supposed to work in the first place.

(I have since rewritten it to zip before converting it to a parallel iterator (as it's not needed):)

```rust
let pairs: Vec<_> = files.into_iter()
    .map(|(path, content)| ((path, content), sender.clone()))
    .collect();
pairs.into_par_iter()
    .for_each(|((path, content), sender)| {
        // do the work
    });
```

**Comment by bluss** [comment]
It's a change from here nikomatsakis/rayon/pull/281 ; the hashmap par iter is not indexable anymore.

**Comment by cuviper** [comment]
Right.  Sorry this wasn't communicated better!

A lot of these collection iterators actually collect into a vector first, and then iterate that in parallel.  But for something like `HashMap`, if we ever got a way to split its internal values (like I'm experimenting [here](https://github.com/cuviper/rayon/blob/hash/rayon-hash/src/par/table.rs#L45)), then this direct parallel iterator couldn't be indexed.  We know how many values are in the map total, but not how many in the upper and lower halves, or in divisions therein.

So the idea was basically: "in a better world where we *don't* have to copy the collection into a vector first, would it still support acting as an indexed producer?"  For the types where that answer is no, we now only support the unindexed iterator methods.

If you'd like to write your code with the exact same behavior as before, it would now look like this:

```rust
let files: HashMap<String, String> = ...;
let senders: Vec<_> = files.iter().map(|_| sender.clone()).collect();
files.into_iter().collect::<Vec<_>>()
    .into_par_iter()
    .zip(senders)
    .for_each(|((path, content), sender)| {
        // do the work
    });
```

And that's almost what you arrived at yourself, just that you don't necessarily need to collect them already zipped together.  It probably doesn't make much difference either way.

**Comment by cuviper** [comment]
BTW, I think your `senders` can be constructed directly as `vec![sender; files.len()]`.  This still clones to every position, but doesn't have to actually iterate the hash table.

I also have some new `ParallelIterator` methods that I'm considering exactly for cases like this, presuming you're talking about `mpsc::Sender` here which is `!Sync`.

```rust
    fn map_with<F, T, R>(self, init: T, map_op: F) -> MapWith<Self, T, F>
        where F: Fn(&mut T, Self::Item) -> R + Sync,
              T: Send + Clone,
              R: Send;

    fn fold_with<F, T>(self, init: T, fold_op: F) -> FoldWith<Self, T, F>
        where F: Fn(T, Self::Item) -> T + Sync,
              T: Send + Clone;
```

I need better names, especially since we already have `Producer::fold_with` that is something completely different.  But the idea is that these would take your `T` (which doesn't have to be `Sync`) and provide it with each item in the iterator, cloning only as necessary for each underlying rayon job.  So if you had say 800 items that end up processing in jobs of 100, then the sender would only be cloned 7 times.

I actually have this working, just need some tests and documentation.  I also considered a variant like `for_each_with`, but you can approximate that using the others as primitives, and we wouldn't want to make `_with` variants of every possible method.

**Comment by robinst** [comment]
Cool, thanks for the detailed explanation! Yeah, I'm using `mpsc::Sender` which unfortunately is not `Sync`. Methods like that would be useful indeed.

(Closing this issue.)
