### ISSUE TITLE
Add an `unordered_map` iterator adapter.

### ISSUE THREAD

**Issue by novacrazy** [nikomatsakis/rayon#338]
For situations where parallel mapping is needed but the order does not need to be preserved, an unordered `map` variation could be faster than the order-preserving adapter. Other than that, it would have the same semantics.

**Comment by cuviper** [comment]
I think it's not quite `map` where we'd need to change anything.  This is already unordered in the way it executes, as the parallel calls will be distributed all over the input.  Or if you do a `for_each`, which is basically a `map` with no result, then there's no visible order at all.

Rather, ordering is preserved when it comes to reduction phases, and for the most part that just falls out naturally from the way we split and re-join the work.  Two closures are passed to `rayon::join`, and two results come back, so it's trivial to keep those in the same order.  There's no benefit to swapping them.

Now, I think we *could* start talking about unordered operations when we have atomic closures ala #141.  We could for instance have an `unordered_collect` which feeds items into a collection as soon as possible, with no regard for input order.  For types that don't maintain insertion order anyway, like the standard maps and sets, they may want to operate this way for plain `collect` too.

Does that make sense?  Are you thinking of something different?

**Comment by novacrazy** [comment]
Hmm.. Yeah, that's basically what I'm going after, but more for the iterator adapter itself and less for `collect()`.

Essentially, I have a few parallel iterators like this:

```rust
// These all map to the same type
let data_set_a = data_set.a.par_iter()   .map(...);
let data_set_b = data_set.b.par_chunks(2).map(...);
let data_set_c = data_set.c.par_chunks(3).map(...);

let data_set = data_set_a.chain(data_set_b).chain(data_set_c);

let result = data_set.fold(...).reduce(...);
```

where it doesn't matter what order the individual subdatasets are passed in, since the fold/reduce operations can work in any order in this case. So I want to be able to squeeze as much performance out of it as possible, and I think avoiding even implicit sorting of the mapped elements could help as it could greedily consume any finished map operation.

Previously, I had tried to do these separately using a unique `fold` operation on each subdataset rather than mapping it to the desired type and running a single `fold`, but the memory pressure of the multiple `fold`s was very heavy, as each one was accumulating the same data type in different buffers.

**Comment by novacrazy** [comment]
Unless `fold` already consumes things out of order?

**Comment by cuviper** [comment]
Ah!  I suspect you're actually encountering a problem with `chain` itself.  [Here](https://github.com/nikomatsakis/rayon/blob/e4fbfa9f1dba4b3e217e35da520a167705dca2a2/src/iter/chain.rs#L49-L51) and [here](https://github.com/nikomatsakis/rayon/blob/e4fbfa9f1dba4b3e217e35da520a167705dca2a2/src/iter/chain.rs#L70-L72) it drives the parallel iterators one after the other, unfortunately not in parallel.  I want to fix that, but the basic problem is that the parallel iterators themselves are not necessarily `Send`, especially when user callbacks are involved since they're only required to be `Sync`.

The `ChainProducer` does truly splice them together, but comes with some extra overhead in tracking chained subsets.  We should do some measurements and see if that's actually enough to matter to performance though.  You only get this producer going through `with_producer`, which you can force by using `enumerate` or `zip`.  (I don't mean that as a long-term solution, just for testing.)

If you have only a few of these, you might also have better luck running them separately in `join`.

```rust
let ((a, b), c) = join(|| join(|| data_set.a.par_iter().map(...).reduce(...),
                               || data_set.b.par_iter().map(...).reduce(...)),
                       || data_set.c.par_iter().map(...).reduce(...));
let abc = a + b + c; // final reduction
```

Of course that loses all the ergonomics of `chain`.  I'll think more on how to properly fix that...

**Comment by cuviper** [comment]
> Unless fold already consumes things out of order?

Note that Rayon's `fold` is really a lot of folds, one for each parallel job.  So each fold job runs in parallel, out of order, but locally a given fold consumes items in order.  That's basically true of `map` too, or anything else -- we divide into parallel jobs, then each of those run sequentially.

If you find that `fold` is getting jobs that are too small to be efficient, you can put a lower bound calling `with_min_len`.  This will also have the effect of forcing `chain` through `with_producer` as noted before.

**Comment by novacrazy** [comment]
When running the parallel iterators with `join`, how do the `join` closures not saturate the thread pool and prevent the parallel iterators from using it? Depending on the number of threads and join closures, that might be the same as running each map/reduce with sequential iterators just on different threads.

**Comment by cuviper** [comment]
The parallel iterators are built on `join` too!  It's fundamental to most rayon patterns that `join` is called recursively like this.

When it's called within the threadpool, `join` doesn't block.  Instead, it queues the second closure and starts running the first.  When that's done it checks if the second is still waiting -- if so it runs it, otherwise it must have been stolen, so this thread will do other work while waiting for that result to come back.

**Comment by novacrazy** [comment]
Interesting, that's a neat way to do it. In fact, that explanation should be added to the documentation of `join` so other's don't misunderstand it like I just did.

As far as the unordered map iterator is concerned, if `map` has almost no overhead to preserve order anyway and all threads are given work until it's done, then I suppose it's fine as is.

**Comment by novacrazy** [comment]
So should we close this or do you think there is anything that can be improved based on this issue? 

I initially opened this because I assumed there would be some overhead with `map` for preserving ordering, and that an eager/greedy algorithm that ignores order could be more efficient and faster. 

However, if that isn't the case, then I think I can close this.

**Comment by cuviper** [comment]
OK, I opened #340 to add a bit to the `join` documentation, and #342 to track the `chain` problem.  I think `map` itself should be fine the way it is.
