### ISSUE TITLE
Using `par_iter::*` is too broad

### ISSUE THREAD

**Issue by cuviper** [nikomatsakis/rayon#59]
The docs recommend `use rayon::par_iter::*;` -- but this includes every `pub mod`, and those have very generic names.  So something simple like this fails:

```rust
use rayon::par_iter::*;
use std::slice;
```

```error: a module named `slice` has already been imported in this module```

If those submodules really need to be public, perhaps there should be a prelude to glob use instead?

**Comment by nikomatsakis** [comment]
Hmm, yes, I was thinking recently that `prelude::*` is more the standard pattern anyway.

**Comment by nikomatsakis** [comment]
I guess the thing to do would be to have `pub mod prelude` in the root level that imports all the `par_iter` traits. Probably not worth putting `join` in there -- I figure people would prefer to write `rayon::join(..)` (or, at least, I would).

(The main reason to have those modules be public is just so that users can name all the intermediate types if they should want to.)

**Comment by cuviper** [comment]
Yeah, I think `join` is too general a name to be a prelude import, and
`rayon::join` is easy enough.  The `par_iter` traits alone would be a great
start for this.

**Comment by nikomatsakis** [comment]
I wonder if it would be helpful to have the prelude include `rayon` itself, so that one can write:

```
use rayon::prelude::*;
...
rayon::join(...)
```
